const { chromium } = require('playwright')
const path = require('node:path')
require('dotenv').config({ path: '/home/syahrul/projects/airis-precia/precia/precia-user-docs/.env.local' })
const { login } = require('/home/syahrul/projects/airis-precia/precia/precia-user-docs/scripts/screenshots/lib/auth')

async function main() {
  const browser = await chromium.launch()
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
  const page = await context.newPage()
  await login(page, 'SUP')
  await page.goto('https://app-dev.precia.site/ai-registry', { waitUntil: 'networkidle' })
  const rowLink = await page.locator('tbody tr:first-child a[href^="/ai-registry/"]')
  const href = await rowLink.getAttribute('href')
  console.log('first module href', href)
  await rowLink.click()
  await page.waitForURL(/\/ai-registry\/.+/, { timeout: 15000 })
  await page.waitForLoadState('networkidle')
  console.log('detail url', page.url())
  await page.screenshot({ path: '/tmp/claude-1000/-home-syahrul-projects-airis-precia-precia/2f0ecae7-a591-45de-8954-d31725803d2c/scratchpad/01-detail.png' })

  const statusBtn = page.locator('button:has(svg.lucide-activity)')
  console.log('statusBtn count', await statusBtn.count())
  await statusBtn.click()
  await page.waitForTimeout(400)
  await page.screenshot({ path: '/tmp/claude-1000/-home-syahrul-projects-airis-precia-precia/2f0ecae7-a591-45de-8954-d31725803d2c/scratchpad/02-status-dialog.png' })
  await page.keyboard.press('Escape').catch(()=>{})

  // close dialog by clicking cancel (footer's first button)
  const cancelBtn = page.locator('.fixed.inset-0 .flex.justify-end.gap-2 button').first()
  await cancelBtn.click()
  await page.waitForTimeout(300)

  const editBtn = page.locator('button:has(svg.lucide-pencil-line)')
  console.log('editBtn count', await editBtn.count())
  await editBtn.click()
  await page.waitForTimeout(400)
  await page.screenshot({ path: '/tmp/claude-1000/-home-syahrul-projects-airis-precia-precia/2f0ecae7-a591-45de-8954-d31725803d2c/scratchpad/03-metadata-dialog.png' })
  const cancelBtn2 = page.locator('.fixed.inset-0 .flex.justify-end.gap-2 button').first()
  await cancelBtn2.click()
  await page.waitForTimeout(300)

  const logBtn = page.locator('button:has(svg.lucide-file-stack)')
  console.log('logBtn count', await logBtn.count())
  await logBtn.click()
  await page.waitForTimeout(1200)
  await page.screenshot({ path: '/tmp/claude-1000/-home-syahrul-projects-airis-precia-precia/2f0ecae7-a591-45de-8954-d31725803d2c/scratchpad/04-log.png', fullPage: true })

  await browser.close()
}
main().catch((e) => { console.error(e); process.exit(1) })
